export const gbooks = [
    {
      id: '1',
      title: "The Martian",
      price: 43.99,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/themartian.jpg",
    },
    {
      id: '2',
      title: "Artemis",
      price: 150,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/artemis.jpeg",
    },
    {
      id: '3',
      title: "Project Hail Mary",
      price: 200,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/hailmary.jpeg",
    },
    { 
      id: '4', 
      title: "Trust", 
      price: 120, 
      rating: { rate: 4.5, count: 1200 },
      img: "/images/trust.jpeg" },
    {
      id: '5',
      title: "Dark Matter: A Novel",
      price: 180,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/dark.jpg",
    },
    {
      id: '6',
      title: "The Object",
      price: 54.99,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/theobject.jpg",
    },
    {
      id: '7',
      title: "Recursion",
      price: 140,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/recursion.jpg",
    },
    { 
      id: '8', 
      title: "Imagine", 
      price: 160, 
      rating: { rate: 4.5, count: 1200 },
      img: "/images/Imagine.jpeg" },
    {
      id: '9',
      title: "Mountain in the Sea",
      price: 130,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/mountain.jpg",
    },
    {
      id: '10',
      title: "Station Eleven",
      price: 89.99,
      rating: { rate: 4.5, count: 1200 },
      img: "/images/stationeleven.jpg",
    },
  ];